---
title: "Homework 6"
author: "Jeffrey Liang"
date: "11/23/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(patchwork)
knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = 8,
  message = F,
  echo = T,
  warning = F
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

# Problem 1

Read in the data.
```{r}
homicide_df = 
  read_csv("data/data-homicides-master/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    ),
    resolved = forcats::fct_relevel(resolved,"unsolved"),
    victim_age = as.numeric(victim_age),
    victim_sex = as.factor(victim_sex)
  ) %>% 
  select(-city,-state,-victim_last,-victim_first,-lon,-lat) %>% 
  filter(!str_detect(city_state,"Tulsa|Dallas|Phoenix|Kansas"),
         victim_race %in% c("White","Black"),
         victim_sex %in% c("Male","Female")) %>% 
  nest(c(-city_state))
```

Do linear regression
```{r}
homicide_df =
  homicide_df %>%
  mutate(log = map(
    .x = data,
    ~ glm(
      resolved ~ victim_age + victim_sex + victim_race,
      data = .x,
      family = binomial()
    )
  ),
  result  = map(log, broom::tidy)) %>% 
  select(-data) %>% 
  unnest(result) %>% 
  mutate(ci = map2(.x = log,
                               .y = term,
                               ~confint(.x,.y))) %>% 
  select(city_state,term,estimate,ci) %>% 
  filter(term == "victim_raceWhite")

homicide_df %>% 
  head() %>% 
  knitr::kable()
```


# Problem 2

Import data
```{r}
birthweight =
  read_csv(here::here("data/birthweight.csv")) %>%
  janitor::clean_names() %>%
  mutate(
    across(
      c("frace", "mrace"),
      ~ case_when(
        .x == 1 ~ "White",
        .x == 2 ~ "Black",
        .x == 3 ~ "Asian",
        .x == 4 ~ "Puero Rican",
        .x == 8 ~ "Other",
        .x == 9 ~ " Unknown"
      )
    ),
    across(where(is.character), as.factor),
    malform = case_when(malform == 0 ~ "absent",
                        malform == 1 ~ "present"),
    malform = as.factor(malform),
    babysex = case_when(babysex == 1 ~ "male",
                        babysex == 2 ~ "female") %>% as.factor()
  )


birthweight %>% skimr::skim_without_charts()
```

We don't know what we interest in, so I just assume to predict birthweight, so 
let first make our data in to cross validation partitions.
```{r cache=T}
set.seed(1)
birthweight_cv =
  modelr::crossv_mc(birthweight, 30, id = "id") %>%
  mutate(
    md_step =
      map(.x = train,  ~ do.call("glm", list(bwt ~ ., data = .x))),
    md_step = map(.x = md_step,
                  ~ step(
                    .x,
                    direction = "both",
                    scope = list(lower = . ~ 1,
                                 upper = . ~ . ^ 2),
                    trace = 0
                  )),
    #is the stepwise model all alike across all cv train?
    md_eg1 =
      map(.x = train,  ~ lm(bwt ~ blength + gaweeks, data = .x)),
    md_eg2 =
      map(.x = train,  ~ lm(bwt ~ blength * bhead * babysex, data = .x)),
    #Fitted the model, now how to verify the prediction?
    rmse_step =
      map2_dbl(.x = md_step,
               .y = test,
               ~ modelr::rmse(.x, .y)),
    rmse_eg1 =
      map2_dbl(.x = md_eg1,
               .y = test,
               ~ modelr::rmse(.x, .y)),
    rmse_eg2 =
      map2_dbl(.x = md_eg2,
               .y = test,
               ~ modelr::rmse(.x, .y))
  )

birthweight_cv %>%
  mutate(across(starts_with("rmse"), as.numeric)) %>%
  pivot_longer(
    starts_with("rmse"),
    values_to = "rmse",
    names_to =  "model",
    names_prefix = "rmse_"
  ) %>%
  ggplot(aes(x = model, y = rmse)) +
  geom_violin()
```

